openapi: 3.2.0
info:
  title: Firecracker Version API
  description: RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
  version: 1.16.0-dev
  termsOfService: ''
  contact:
    email: firecracker-maintainers@amazon.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://localhost/
tags:
- name: Version
paths:
  /version:
    get:
      summary: Gets the Firecracker version
      operationId: getFirecrackerVersion
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FirecrackerVersion'
        default:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      tags:
      - Version
components:
  schemas:
    Error:
      type: object
      properties:
        fault_message:
          type: string
          description: A description of the error condition
          readOnly: true
    FirecrackerVersion:
      type: object
      description: Describes the Firecracker version.
      required:
      - firecracker_version
      properties:
        firecracker_version:
          description: Firecracker build version.
          type: string
