swagger: '2.0'
info:
  title: Firecracker Actions Version API
  description: RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
  version: 1.16.0-dev
  termsOfService: ''
  contact:
    email: firecracker-maintainers@amazon.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
tags:
- name: Version
paths:
  /version:
    get:
      summary: Gets the Firecracker version.
      operationId: getFirecrackerVersion
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/FirecrackerVersion'
        default:
          description: Internal server error
          schema:
            $ref: '#/definitions/Error'
      tags:
      - Version
definitions:
  Error:
    type: object
    properties:
      fault_message:
        type: string
        description: A description of the error condition
        readOnly: true
  FirecrackerVersion:
    type: object
    description: Describes the Firecracker version.
    required:
    - firecracker_version
    properties:
      firecracker_version:
        description: Firecracker build version.
        type: string
