openapi: 3.2.0
info:
  title: Firecracker Actions API
  description: RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. The transport medium is a Unix Domain Socket.
  version: 1.16.0-dev
  termsOfService: ''
  contact:
    email: firecracker-maintainers@amazon.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://localhost/
tags:
- name: Actions
paths:
  /actions:
    put:
      summary: Creates a synchronous action
      operationId: createSyncAction
      responses:
        204:
          description: The update was successful
        400:
          description: The action cannot be executed due to bad input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InstanceActionInfo'
        required: true
      tags:
      - Actions
components:
  schemas:
    InstanceActionInfo:
      type: object
      description: Variant wrapper containing the real action.
      required:
      - action_type
      properties:
        action_type:
          description: Enumeration indicating what type of action is contained in the payload
          type: string
          enum:
          - FlushMetrics
          - InstanceStart
          - SendCtrlAltDel
    Error:
      type: object
      properties:
        fault_message:
          type: string
          description: A description of the error condition
          readOnly: true
